### ISSUE TITLE
npm ERR! Could not install from "node_modules/sails-mysql-transactions/waterline" as it does not contain a package.json file.

### ISSUE THREAD

**Issue by AskYous** [postmanlabs/sails-mysql-transactions#69]
**Operating System:** iOS
**Node version**: v9.7.1
**NPM version**: 5.7.1

---

The following error occurs when I try installing `sails-mysql-transactions` by running `sudo npm install sails-mysql-transactions --save`:

---

```
sjca1yshapro:fly-high-training mlgyshan$ sudo npm install sails-mysql-transactions --save
Password:
Unhandled rejection Error: Command failed: /usr/local/bin/git clone --depth=1 -q -b v0.5.1-postman.3 https://github.com/postmanlabs/waterline-sequel.git /Users/mlgyshan/.npm/_cacache/tmp/git-clone-cd22e129
/Users/mlgyshan/.npm/_cacache/tmp/git-clone-cd22e129/.git: Permission denied

    at ChildProcess.exithandler (child_process.js:273:12)
    at ChildProcess.emit (events.js:127:13)
    at maybeClose (internal/child_process.js:936:16)
    at Socket.stream.socket.on (internal/child_process.js:353:11)
    at Socket.emit (events.js:127:13)
    at Pipe._handle.close [as _onclose] (net.js:558:12)


> sails-mysql-transactions@0.8.3-hotfix.4 postinstall /Users/mlgyshan/fly-high-training/node_modules/sails-mysql-transactions
> scripts/postinstall.sh

sails-mysql-transactions: Injecting waterline into sails...
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
removed 8 packages in 59.246s
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/sails-mysql-transactions/waterline" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mlgyshan/.npm/_logs/2018-03-13T18_49_48_885Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sails-mysql-transactions@0.8.3-hotfix.4 postinstall: `scripts/postinstall.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sails-mysql-transactions@0.8.3-hotfix.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mlgyshan/.npm/_logs/2018-03-13T18_49_49_551Z-debug.log
```
Here is [my log file](https://gist.github.com/AskYous/15eeb7f3e20b6a988c8c816eacd54dd1).

**Comment by dreamkyr** [comment]
I have exactly same issue.
node v10.1.0,
npm v5.6.0,
MacOS 10.13

**Comment by kunagpal** [comment]
Hey @AskYous @thomasgit123 Sails v1 comes with inbuilt support for transactions, as can be seen here: https://sailsjs.com/documentation/reference/waterline-orm/datastores/transaction.
